[profile.default]
src = "src"
out = "out"
libs = ["lib"]
[rpc_endpoints]
mainnet = "${https://eth-mainnet.g.alchemy.com/v2/ta9Dz7jBlyvxEd4WjZhBt}"
arbitrum = "${https://arb-mainnet.g.alchemy.com/v2/1DlieFmqqBPXqKq910wEr}"

[invariant]
runs = 256
depth = 30
fail_on_revert = false

# Жестко фиксируем версию компилятора, чтобы у всей команды среда была идентичной
solc = "0.8.24"

# Включаем оптимизатор Solidity для минимизации затрат на газ при деплое пулов и токенов
optimizer = true
optimizer_runs = 200

# Включаем продвинутый оптимизатор EVM (via-ir), он необходим для сложных DeFi структур и Yul-кода
via_ir = true

# Настройки генерации отчетов по газу (Gas Report)
gas_reports = ["*"]

# Настройка вывода предупреждений компилятора (делаем код чистым)
ignored_error_codes = [1878] # Игнорируем предупреждения о лицензиях в зависимостях, если они будут

[profile.ci]
# Специальный профиль для GitHub Actions, чтобы тесты в облаке не тратили лишнее время
fuzz = { runs = 256 }
invariant = { runs = 10, depth = 15 }